name: WebDocument

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Deploy
      env:
        CI_PUSH_TOKEN: ${{ secrets.CI_PUSH_TOKEN }}
      run: |
        choco install -y docfx
        choco install -y doxygen.install
        git clone https://lriki:${CI_PUSH_TOKEN}@github.com/LuminoEngine/LuminoEngine.github.io.git _docs_repo
        python clearn_deploy_target.py
        python build.py
        cp -rf _site _docs_repo
        cd _docs_repo
        git config user.name "LuminoEngine"
        git config user.email "LuminoEngine@users.noreply.github.com"
        git config core.autoCRLF false
        git add .
        git commit -m '[CI] Deploy to GitHub Pages'
        git push origin master
